#mongodb
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: homebrew

#logging
logging:
  level:
    org:
      springframework:
        data: debug
        web: debug
